name: registration_form
description: A simple application to validate the data in the registration form.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^4.3.2+1
  rxdart: ^0.24.0
  responsive_builder: ^0.2.0+2
  intl: ^0.17.0-nullsafety.2
  retrofit: any
  logger: any
  json_annotation: any
  reflectable: ^2.2.4
  mockito: 4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  build_runner: any
  json_serializable: any

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
